import type { Position } from "./player-types";

export type NarrativeContext = Record<string, string | number>;

/** Replaces {token} placeholders. Unknown tokens are left untouched. */
export function fill(template: string, context: NarrativeContext): string {
  return template.replace(/\{(\w+)\}/g, (token, key: string) => {
    const value = context[key];

    return value === undefined ? token : String(value);
  });
}

export type RatingBand = "low" | "mid" | "high";

export function bandFromRating(rating: number): RatingBand {
  if (rating >= 8.2) {
    return "high";
  }

  if (rating >= 5.2) {
    return "mid";
  }

  return "low";
}

/* ------------------------------------------------------------------ */
/* High-school origin story — openings                                 */
/* ------------------------------------------------------------------ */

export const HS_OPENINGS: string[] = [
  "{first} grew up eight minutes from the {hs} field house and knew the {mascot} playbook before he had pads.",
  "{last} showed up at {hs} a skinny freshman with no film and an older brother who never made it.",
  "Everybody in {city} knew the {last} name. {first} is the one who checked every box past eighth grade.",
  "The {hs} staff found {first} in a middle-school gym class and spent four years keeping him in one sport.",
  "{name} took his first varsity snap the night two starters went down in the same quarter.",
  "{city} is a basketball town, which is why {last} spent two years as an afterthought at {hs}.",
  "{first} came up through the {mascot} youth program and never considered playing anywhere else.",
  "{last} transferred into {hs} before his sophomore year and changed what the {mascot} could run.",
  "{name} was the third-string {pos} as a freshman and the only one still on the roster by spring.",
  "There is a photo of {first} at 14 in the {hs} weight room. Nobody believes the before-and-after.",
  "The {mascot} had not won a league title in nineteen years when {last} arrived at 5'6\".",
  "{name} started playing in seventh grade, on a {city} team that went winless.",
  "His mother made him wait for tackle football, so {hs} got him with almost no bad habits.",
  "{last} spent his freshman year on scout team and his sophomore year making the varsity regret it.",
  "{first} was a {city} youth-league legend, which in {state} means the whole county knew the name.",
  "The film that made {name} a name in the {state} recruiting cycle was shot on a phone from the bleachers.",
  "{hs} has sent two players to Division I. {last} spent four years determined to be the third.",
  "{name} showed up to his first {mascot} camp at 152 pounds and left the most explosive player there.",
  "{last} played both lines as a freshman because {hs} did not have the bodies to specialize.",
  "In {city}, Friday nights are the whole economy, and {first} was who people drove in to watch.",
  "{name} was cut from his eighth-grade team. The {hs} staff tells that story to every scout who calls.",
  "The {mascot} moved {last} to {pos} his sophomore spring and never considered moving him back.",
  "{first} grew up two blocks from a Division I campus, sneaking into their spring practices.",
  "{name} is the youngest of four. The other three played at {hs} without a single college look.",
  "{last} came to {hs} from a middle school that did not have a football program at all.",
  "The first evaluator into {hs} for {first} was assumed to be there about someone else.",
  "{name} began as the {mascot}' backup punter and finished the most recruited name in {state}.",
  "There is a version of this where {last} plays mid-major basketball and nobody ever finds out.",
  "{first} was 6'1\" as a freshman, and {city} spent three years waiting on the rest of the frame.",
  "{name} had one offer as a sophomore, from a school that has since fired the coach who made it.",
  "{last} worked summers at a warehouse outside {city} and trained at 5 a.m. before his shifts.",
  "{hs} carries 41 players, which is why {first} played about 90 snaps a night.",
  "The {mascot} were 2-8 before {name} took over and in the state semifinal two years later.",
  "{first} committed to the first school that offered, then spent a year outgrowing that choice.",
  "{name} is the kind of {state} riser who gets found at a 7-on-7 three states from home.",
  "{last} played quarterback, safety and returned kicks because {hs} could not afford to rest him.",
  "The {hs} weight-room record board has {first}'s name on it four times.",
  "{name} did not start until his junior year, which remains the key variable in his projection.",
  "{first} moved to {city} before sophomore year and sat out half a season under transfer rules.",
  "{last} was a 190-pound freshman who told the {hs} staff he would play on Sundays.",
  "{first} broke his wrist the summer before ninth grade and spent the recovery watching film instead of scrolling his phone.",
  "The {hs} equipment room ran out of shoulder pads his freshman year, which tells you something about how fast he grew.",
  "{last} rode two buses to get to {hs} every morning, then stayed late enough to catch the last one home.",
  "Nobody in {city} remembers {first} losing a foot race until he was already the best player on the team.",
  "The {mascot} had four different starting quarterbacks in three years before {last} took the job and never let it go.",
  "{first} spent his freshman summer working construction with his uncle, which is where the frame actually came from.",
  "{name} once played an entire quarter with a dislocated finger and nobody on the sideline noticed until halftime.",
  "The {hs} film room still has a breakdown of {last}'s eighth-grade tape, kept as a joke that stopped being funny.",
  "{first} grew up coaching his little brothers in the backyard before he ever started for {hs} himself.",
  "{last} showed up to his first varsity practice in cleats two sizes too big, borrowed from a cousin who had quit.",
  "The {mascot} coaching staff nearly cut {first} as a freshman before a summer growth spurt changed the conversation.",
  "{name} learned the {pos} position from an assistant coach who ran the JV program like a college staff meeting.",
  "There was no varsity depth chart with {last}'s name on it until a Tuesday practice in October changed everything.",
  "{first} played travel basketball into his junior year, which is the reason his recruitment started so late.",
  "The {hs} weight room opens at 5:30 in the morning, and {last} was the only underclassman who ever showed.",
  "{name} grew up watching {mascot} film with his grandfather, who never once believed the hype until he saw it live.",
  "A torn ACL in eighth grade nearly ended things before they started, and {first} still talks about the rehab.",
  "{last} was the smallest kid at every camp he attended until the spring before his junior year.",
  "The {mascot} moved practice indoors that August, and {name} used the extra reps to rebuild his footwork entirely.",
  "{first} grew up in a house that measured success by tackles for loss, not touchdowns, and it shows on tape.",
  "{last} spent two years as the {hs} kicker before a coach noticed he could do more than that.",
  "There is a version of {name}'s freshman tape that the coaching staff refuses to show anyone outside the building.",
  "{first} learned the game from his older sister, who played quarterback in a men's league nobody outside {city} has heard of.",
  "The {mascot} had exactly one winning season in a decade before {last} arrived and flipped the program's identity.",
  "{name} missed his entire sophomore season with mono, which is the answer to the question every scout eventually asks.",
  "{first} grew up three hours from the nearest Division I campus and made the drive to camps every summer regardless.",
  "{last} was cut from the {hs} basketball team as a sophomore, which the football staff still brings up at banquets.",
  "The tape that got {name} noticed was shot by a parent on a tripod nobody set up correctly.",
  "{first} played up two grade levels as a freshman because {hs} did not have a true freshman team.",
  "{last} broke his own {hs} single-game rushing record twice in the same season, three weeks apart.",
  "{name} spent his middle-school years as a soccer goalkeeper, which explains the footwork nobody else at {pos} has.",
  "The {mascot} staff redshirted {first} as a true freshman by design, and the payoff showed up two years later.",
  "{last} grew up going to {hs} games before he could walk, and the program still has the ticket stub to prove it.",
  "{name} was benched for the entire first half of his sophomore opener and finished the year as the starter.",
  "{first} trained at a facility two towns over because {hs} did not have anyone who coached his specific position.",
];

/* ------------------------------------------------------------------ */
/* High-school origin story — development beats                        */
/* ------------------------------------------------------------------ */

export const HS_BEATS: string[] = [
  "He moved into the starting lineup midway through his sophomore season and never came off the field again.",
  "A spring growth spurt reshaped his frame, and the staff stopped treating him like a developmental project.",
  "By his junior year the {mascot} were building game plans around one side of the formation.",
  "He spent two summers on the camp circuit before the buzz finally caught up to the tape.",
  "A regional semifinal against the state's top-ranked defense became the tape everyone eventually watched.",
  "The rivalry game his junior year is still the clip that gets passed around {city} group chats.",
  "He added 22 pounds between his sophomore and junior seasons without giving back any short-area burst.",
  "A high-ankle sprain cost him four games as a junior, which is the only reason his junior tape is thin.",
  "The {mascot} moved him everywhere, because leaving him in one spot let defenses key on him.",
  "He tested well enough at a spring camp that two staffs drove out to {city} the following week.",
  "His position coach at {hs} had a decade in the college game and installed a pro-caliber pre-snap routine.",
  "He played through a torn thumb ligament in the playoffs — the kind of detail area scouts write down.",
  "A November quarterfinal in the mud is the game the {hs} staff still shows to freshmen.",
  "He captained the {mascot} as a junior, which the program had not done in over twenty years.",
  "The {hs} staff put him on a strength program in January and he came back in August a different athlete.",
  "He won his flight at a national camp in June and the first Power-conference offer came four days later.",
  "Two years of 7-on-7 in the offseason cleaned up the parts of his game Friday nights never exposed.",
  "He spent his junior offseason working with a private coach in {city} who had trained two NFL players.",
  "The {mascot} lost in the second round three years running, and he is the reason they were even there.",
  "He set the {hs} single-game record in a Week 4 blowout, then apologized for the running clock.",
  "A midseason position change unlocked everything — the production doubled inside five weeks.",
  "The {city} paper ran a full page on him, and the highlight reel found its first 10,000 views.",
  "He played the entire second half of his junior year with a brace on his left knee.",
  "Coordinators started scheming him out of games, and that tape is oddly the most convincing evidence.",
  "He weighed 214 pounds at his junior evaluation and 236 pounds at his senior opener.",
  "The {mascot} played a national schedule his senior year specifically to get him seen.",
  "He was the only underclassman invited to a regional showcase in {state} his sophomore spring.",
  "Winter track was the difference — the testing numbers he posted in February changed how staffs read him.",
  "He was benched for a half as a sophomore for missing a workout and has not missed one since.",
  "A four-touchdown night against the eventual state champion is what put him on the national board.",
  "The {hs} staff started limiting his snaps in blowouts because the score got out of hand so fast.",
  "He learned three positions in one offseason after the {mascot} lost six seniors to graduation.",
  "His senior film opens with a play he finished 40 yards from where he lined up.",
  "Camp evaluators kept writing the same note: the frame has real room left on it.",
  "He committed in July, decommitted in November, and handled both news cycles better than most adults would.",
  "The {mascot} went to overtime three times his senior year and he touched the ball on every snap that mattered.",
  "A hamstring injury in the spring of his junior year cost him the entire camp circuit.",
  "He played both ways in the playoffs because the {hs} staff had no other option left.",
  "By October of his senior year, teams were kicking away from him and running away from his side.",
  "He closed a 12-game senior season without a single missed assignment on the coaching staff's grade sheet.",
  "The {hs} strength coach still uses his squat progression as the program's blueprint.",
  "Two of his teammates drew offers off the back of his film, which is the kind of detail staffs notice.",
  "He was voted team MVP as a junior over a senior who ended up signing at a Power program.",
  "A cross-state showcase in June is where the national recruiting media finally caught up to him.",
  "He spent his last two summers running youth camps in {city} and got noticeably sharper explaining the game.",
  "His junior tape and senior tape read like two different evaluations, which is exactly the point.",
  "The {mascot} ran the same play at him eleven times in the playoff opener and it never worked once.",
  "He is the only player in {hs} history to start on both sides of the ball in a state final.",
  "The staff moved him to a new spot in Week 6, and he graded out as the best player on the field by Week 8.",
  "He played the last month of his senior season at roughly 85 percent and it barely showed on tape.",
  "A viral one-handed catch in September did more for his recruitment than two years of consistent tape.",
  "The {hs} coaching staff still calls his senior year the best individual season they have ever coached.",
  "He never lost a rep in one-on-ones at a national camp, and the clip still circulates.",
  "His last regular-season game ended with the opposing coach crossing the field to shake his hand.",
  "He added a full step of long speed between his sophomore and junior seasons without changing his training at all.",
  "A joint practice against the state's top-ranked team is the first tape that made outside evaluators pay attention.",
  "He turned down a chance to play up a level as a sophomore, wanting to be the guy at {hs} instead.",
  "The {mascot} ran a no-huddle package built entirely around his conditioning advantage over the defense.",
  "He missed two weeks with a stinger as a junior and came back playing angrier than before it happened.",
  "A summer at an out-of-state camp exposed a technical flaw nobody at {hs} had caught, and he fixed it by August.",
  "The {city} all-star game that fall is still the measuring stick local coaches use for every prospect after him.",
  "He played every special-teams snap available as a sophomore just to stay on the field.",
  "A coaching change at {hs} his junior year could have derailed things; instead the new staff built around him.",
  "He turned a broken play into the signature highlight of his junior season, and it still gets replayed at pep rallies.",
  "The {mascot} lost their starting quarterback in Week 2, and he adjusted his own game to cover the gap.",
  "He spent an entire offseason adding muscle in places that do not show up on a stat sheet.",
  "A scrimmage against a Power-conference commit that August is the tape his position coach still keeps on his phone.",
  "He earned a scholarship offer standing on the sideline in street clothes, rehabbing an injury nobody saw coming.",
  "The {hs} staff moved practice to 6 a.m. that fall specifically because of how hard he pushed the tempo.",
  "He was the only sophomore who dressed for varsity that year, and the staff never regretted the decision.",
  "A summer growth spurt added three inches and somehow made him faster, not slower.",
  "He turned an ordinary Tuesday walk-through into a teaching tape the {hs} staff still uses with freshmen.",
  "The {mascot} installed a package specifically to get him the ball in space, and it never stopped working.",
  "He requested extra film sessions on his own time, which is the detail his position coach mentions first.",
  "A four-interception night as a junior is the game that turned a regional name into a state one.",
  "He carried an entire receiving room on his back for six weeks after two teammates went down to injury.",
  "The {hs} strength staff still measures new freshmen against the numbers he posted as a sophomore.",
  "He changed his diet on his own initiative going into his junior year and the tape noticeably sped up.",
  "A missed extra point cost the {mascot} a game his sophomore year, and he never let a special-teams rep go unprepared again.",
  "He earned the starting job in fall camp over an upperclassman who had held it for two years.",
  "The rivalry win his senior year is the last thing most of {city} remembers about that season.",
  "He played the second half of his junior season with a wrapped ankle and never once brought it up publicly.",
  "A four-touchdown comeback in the fourth quarter of a semifinal is the reason his recruitment doubled overnight.",
  "He spent the summer before his senior year training with two former {hs} players who had already made the league.",
  "The {mascot} staff gave him defensive reps as a senior purely to keep him fresh for special teams.",
  "He turned a routine sophomore practice rep into the play his coaches still show recruits on visits.",
  "A quiet junior season became a loud senior one the moment the coordinator handed him the offense.",
  "He earned every rep back after a benching, which the staff calls the best thing that happened to him.",
  "The {hs} equipment staff had to special-order cleats for him by his junior year — an easy story that always comes up.",
  "He turned down a chance to redshirt a grade and play up two levels; the staff still isn't sure that was the right call.",
  "A summer camp performance three states away is the reason his name reached evaluators who never watch {state} film.",
  "He set the tone in warmups so consistently that opposing teams started scouting the pregame routine.",
  "The {mascot} lost a heartbreaker in the regional final his junior year, and he cried in the locker room longer than anyone.",
  "He added a legitimate second gear in the open field that nobody projected from his sophomore tape.",
  "A teacher recommendation letter, not a highlight reel, is what actually got one key program to visit {hs}.",
  "He turned a position change forced by injuries into the best year of his high-school career.",
  "The {hs} staff still argues about whether his junior or senior season was the better tape.",
  "He never asked out of a single rep in four years, which his coaches call the most underrated stat in his file.",
  "A two-way workload that would exhaust most seniors barely seemed to register with him.",
];

/* ------------------------------------------------------------------ */
/* High-school origin story — closings                                 */
/* ------------------------------------------------------------------ */

export const HS_CLOSINGS: string[] = [
  "He finished his senior year as the most complete player on the field on most Friday nights in {state}.",
  "By signing day, the projection was simple: give him a college weight program and see what is left.",
  "He closed his career at {hs} with a district title and a frame that was clearly not finished growing.",
  "The senior tape was clean enough that questions about talent gave way to questions about scheme fit.",
  "He left {hs} as the program's most decorated player since the early 2000s.",
  "The senior season answered the durability question and raised a much better one about the ceiling.",
  "Evaluators left {city} agreeing on the traits and disagreeing about how fast they translate on Saturdays.",
  "He graduated early to enroll in January, which told everyone how seriously he took the next step.",
  "The last three games of his senior year were the best football anyone in the county had seen in a decade.",
  "He signed in December and was in a college weight room before his classmates finished the semester.",
  "The {mascot} retired his number, which for a program that age is not a small gesture.",
  "He left {city} with the school records and a very short list of people who thought he was finished improving.",
  "Recruiting analysts spent his senior year arguing about his ranking and never once about his tape.",
  "The final evaluation read like a bet on the frame as much as a bet on the production.",
  "He walked out of {hs} with a body that already looked collegiate and a technique base still catching up.",
  "His senior year ended in a state semifinal loss that the {city} paper covered like a wake.",
  "By the end, the only real question was which position a college staff would let him keep.",
  "He committed on a Tuesday in a nearly empty {hs} gym and asked the staff not to make it a ceremony.",
  "The staff's parting evaluation was two words: not finished.",
  "He left as the best player any of those coaches had ever put on a field, and they had coached a long time.",
  "The projection was never complicated — add weight, keep the speed, let him play fast.",
  "He ended his high-school career with more college interest than the previous five {hs} classes combined.",
  "Nobody in {city} was surprised by where he signed. Plenty were surprised by who else was in it.",
  "He finished the year as an all-state selection and the least surprised person in the room about it.",
  "His last game at {hs} drew more college assistants than the {mascot} usually draw fans.",
  "The tape closed the argument. The measurements reopened it, which is how these things always go.",
  "He spent his final semester adding weight on purpose and lost nothing off his timed speed doing it.",
  "By February he was already enrolled, already in the install, and already ahead of his class.",
  "He left {hs} without a single bad season, which is rarer than the highlight reel makes it look.",
  "The last thing his {hs} coach told recruiters was that they were getting the best worker in the building.",
  "He signed with the program that wanted him since his sophomore film, and the loyalty was the whole story.",
  "His senior season was good enough to end the debate and short enough to leave people wanting more.",
  "The {mascot} have not replaced him. Three years later, they are still not close.",
  "He left {hs} with a legacy the underclassmen were still talking about a full recruiting cycle later.",
  "The staff's final word on him was simple: whatever level he plays at, he will outwork the room.",
  "He signed having never once discussed his ranking publicly, which his coaches say was entirely on purpose.",
  "By the time he graduated, {hs} had rewritten its record book almost entirely around his senior year.",
  "The tape and the person both checked out, which evaluators will tell you does not happen as often as it should.",
  "He left the program in better shape than he found it, on the field and in the weight room both.",
  "His senior banquet ran long because nobody on the coaching staff wanted to stop talking about him.",
  "The {mascot} program's next great hope will be measured against him for at least a decade.",
  "He signed his letter of intent in the {hs} gym in front of the entire underclass, on purpose.",
  "The last evaluator to leave {city} that fall left with the same note everyone else already had.",
  "He finished high school as the answer to a question nobody in {state} had thought to ask yet.",
  "The staff's parting gift was a locker with his number retired before he had even left campus.",
  "He walked away from {hs} having never missed a rep he was healthy enough to take.",
  "The recruiting rankings eventually caught up to what {hs} already knew about him.",
  "He left having proven the one thing every coach wants proven: the tape was not the ceiling.",
  "By signing day, the only debate left was how quickly the redshirt year would actually last.",
  "He closed his high-school career the same way he opened it — quietly, and completely under control.",
  "The {hs} staff's final evaluation fit on an index card: special player, more special person.",
  "He left {city} the way most legends do, with more stories than anyone could verify.",
  "The program's youth camp numbers doubled the year after he signed, which the staff credits entirely to him.",
  "He finished his senior season with a highlight reel that needed no music to hold anyone's attention.",
  "The last thing he did at {hs} was help the next kid at his spot learn the position he was leaving behind.",
  "He left having never once made a coach regret handing him the keys.",
  "The evaluation was finished by October of his senior year; the rest of the season was just confirmation.",
  "He signed on national signing day surrounded by a class of {hs} teammates headed to programs of their own.",
  "The {mascot} banner with his number still hangs in the gym, a full class ahead of the ones who remember why.",
  "He left {hs} having turned a program most people had written off into one people now watch on purpose.",
  "The final read on him was unanimous in a way recruiting evaluations almost never are.",
  "He walked off the field for the last time at {hs} to an ovation from people who had booed the program two years earlier.",
  "By the time it was over, the only people still debating his ceiling were the ones who had never seen him play.",
];

/* ------------------------------------------------------------------ */
/* Recruiting / offer-market story                                     */
/* ------------------------------------------------------------------ */

type RecruitingBank = {
  found: string[];
  rise: string[];
  pitch: string[];
  scope: string[];
};

export const RECRUITING_BANKS: Record<RatingBand, RecruitingBank> = {
  low: {
    found: [
      "Area recruiters found him on a junior-varsity cutup a {hs} assistant mailed out unprompted.",
      "His first real contact came from a {topOffer} grad assistant in {state} to see somebody else entirely.",
      "He was a name on a regional board for two years before anybody scheduled a home visit.",
      "The first coach through the door at {hs} was recruiting a teammate and left asking about {last}.",
      "A {topOffer} area scout stopped in {city} on the way back from a bigger evaluation and stayed the practice.",
      "His {hs} coach called in a favor with an old {topOffer} colleague just to get the film watched at all.",
      "He got found the way most players at this level do — a staff needed a body and started asking around.",
      "The first offer came from a program that had signed two players out of {city} in the previous decade.",
      "He filled out a recruiting questionnaire in September and heard back from four schools the same week.",
      "A regional camp in {state} put him on a list, and that list is the only reason anybody called.",
      "His tape sat at 300 views until a {state} analyst posted it in a thread about overlooked seniors.",
      "The {hs} staff sent film to 40 programs. Six responded, and three of those were form letters.",
      "Everybody who eventually offered had driven through {city} before, just never stopped for him specifically.",
      "In a town the size of {city}, word of mouth from the {hs} staff is still how most of this starts.",
      "The nearest FBS staff to {city} is the one that found him first, which is how it usually goes at this level.",
      "The {hs} highlight tape sat untouched on a recruiting site for a year before a small-school coach clicked play out of boredom.",
      "A regional 7-on-7 roster spot, filled at the last minute, is the entire reason anyone outside {city} found him.",
      "His name first appeared on a board because a scout was actually there to see a teammate's little brother.",
      "A {topOffer} assistant found the tape while researching an entirely different recruiting class.",
      "The first call came from a school {last} had never heard of, recruiting a position he had not played since freshman year.",
      "He got discovered the unglamorous way — a coach cold-called {hs} because the area code matched a hunch.",
      "A stack of unopened recruiting letters sat on the kitchen table for weeks before anyone understood what they meant.",
      "The tape that started it all was filmed sideways and uploaded by a parent who did not know how to fix it.",
      "His recruitment technically started with a form email that the {hs} staff almost deleted as spam.",
    ],
    rise: [
      "A strong senior October moved him from a preferred-walk-on chat to a real scholarship conversation.",
      "One spring camp performance in front of three staffs did more for his stock than two years of film.",
      "He never had a signature summer, so the offers came late and arrived in a cluster.",
      "The offers landed after Thanksgiving, once staffs finished missing on higher-rated targets.",
      "He grew an inch and a half between June and December, which quietly rewrote his entire evaluation.",
      "Two schools offered inside the same 48 hours in January — a classic sign of a late film cycle.",
      "The rise, such as it was, came from testing numbers rather than the fall tape.",
      "A strong senior-night showing in front of a visiting coordinator changed the tone of his recruitment.",
      "He was a fallback option for two staffs and became a priority for one of them by December.",
      "The board did not really move until he committed and rival schools started calling to check.",
      "His entire recruitment lived in the last eight weeks before signing day.",
      "He landed his best offer the week after a higher-rated prospect at his spot picked somewhere else.",
      "A two-week stretch of standout practices at a regional camp is the entire recruitment, condensed.",
      "He picked up his only two offers on the same Friday, four months apart from each other's original interest.",
      "The rise came quietly, one grainy highlight clip at a time, until the offer count finally caught up.",
      "Nothing about his recruitment moved until a rival's decommitment opened a roster spot in January.",
      "He added twenty pounds of muscle between his junior and senior seasons, and the offer sheet noticed before the tape did.",
      "A late scholarship opened up unexpectedly, and he happened to be the name at the top of somebody's backup list.",
      "His recruitment stalled for months before one open tryout changed the entire conversation.",
      "The offers arrived in the order of who actually needed a body at his position, not who wanted him most.",
      "A cousin's college teammate made one phone call, and that is the honest story behind his only Power-conference look.",
    ],
    pitch: [
      "Every pitch here is a development pitch: two years in the weight room and a redshirt to finish the frame.",
      "Staffs are selling scheme fit and a defined role rather than stars or national rankings.",
      "The sell is opportunity — he can be on the two-deep as a true freshman at this level.",
      "Coaches like the floor: immediate special-teams value, a starter's body by year three.",
      "One staff is pitching a position change that would take real patience from both sides.",
      "There is no meaningful NIL conversation here, and everybody involved already knows it.",
      "The pitch is proximity — his family can drive to every home game without missing work.",
      "One program is selling a coordinator who has developed three players out of nearly identical profiles.",
      "Coaches keep using the word project, which he has decided to wear as a compliment.",
      "The pitch is opportunity: the position room graduates three seniors after next season.",
      "Staffs are upfront about the redshirt, and he seems to prefer that to being oversold.",
      "The best offer on his board comes with an academic package that matters as much as the football one.",
      "The pitch is blunt: come in, add weight, and see if the tools translate once the pads come on for real.",
      "Every program on his board is selling the exact same thing — a shot, nothing guaranteed beyond it.",
      "One staff is upfront that he would be the fourth option at his spot in year one, and he respects the honesty.",
      "The sales pitch here is geography as much as anything — closest school, smallest travel budget, easiest decision.",
      "Coaches keep telling him the tape translates; the roster spot is the only thing actually on the table.",
      "The pitch amounts to a locker, a helmet, and an open competition with no promises attached to any of it.",
      "One program is selling him on special teams as the fastest path onto the field, and he has taken the hint.",
      "The only real pitch left on his board is patience — from him, and from whichever staff signs him.",
      "Every conversation eventually gets to the same place: prove it in camp, and the roster spot follows.",
    ],
    scope: [
      "This is a regional recruitment. The board never left {state} and the two states next to it.",
      "The market stayed local, exactly how the {hs} staff figured it would go.",
      "He is a G5 and FCS target with no realistic Power-conference pressure on the timeline.",
      "The recruitment is quiet, close to home, and likely decided by whichever staff visits last.",
      "Three schools are in it, all within a four-hour drive of {city}.",
      "Nobody outside the region has called, and the {hs} staff stopped expecting them to in October.",
      "His entire recruitment happened over the phone and in one living room in {city}.",
      "It is a two-team race between a G5 program and an FCS program offering a bigger role.",
      "The board is small enough that he knows every assistant on it by first name.",
      "This is the kind of recruitment that gets settled by whichever staff keeps calling in January.",
      "He took two official visits and paid his own way to a third.",
      "The recruitment never generated a single national headline, which suits him just fine.",
      "Everyone involved understands this is a {state} kid who is going to end up at a {state} school.",
      "{city} will get to watch almost every game he plays in college, and that mattered to his family.",
      "This is small-town recruiting — three assistant coaches, one gas station, and a lot of repeat visits.",
      "This recruitment is one zip code wide, and everyone involved is fine with that.",
      "The whole process took place over four phone calls and a single unofficial visit paid for out of pocket.",
      "Nobody outside a two-hour radius of {city} has expressed interest, and the family stopped expecting otherwise.",
      "The board is one school deep most weeks, occasionally two.",
      "This is the definition of a homegrown recruitment — one program, one commitment, no drama attached.",
      "The recruitment never left the county line, and the {hs} staff never expected it to.",
      "He is choosing between two programs that share a conference and a recruiting footprint the size of {state}.",
      "The whole board fits on the back of a single roster page.",
      "This recruitment will end quietly, the way most of them do at this level, with a phone call nobody outside the family hears.",
    ],
  },
  mid: {
    found: [
      "He built his board the honest way, camping at four schools in one June and drawing offers from three.",
      "A regional recruiting analyst slotted him into a summer top-25 for {state} and the phone started ringing.",
      "Two Power-conference staffs offered inside the same week after his junior film hit the portal of tape.",
      "He had a standing G5 offer since sophomore spring, which gave him leverage to be patient.",
      "The {topOffer} staff offered first and spent the next eight months defending that position on the board.",
      "A coordinator watched him at a satellite camp in {state} and called his {hs} coach from the parking lot.",
      "He showed up unranked to a national camp in June and left with three new offers and real buzz.",
      "His junior tape got passed between two staffs on the same conference call — how these things spread.",
      "A regional analyst wrote 400 words about him in July, and the offer count doubled inside a month.",
      "He was the second-best player on his own team as a sophomore, which is why the discovery took so long.",
      "The first Power-conference coach to see him in person came to {city} for a teammate and left with two names.",
      "A strong showing at a spring showcase in {state} moved him onto boards three states away.",
      "{city} does not produce a Power-conference prospect every year, so this recruitment got noticed locally fast.",
      "A regional analyst stumbled onto his tape while researching a completely different position group.",
      "Two assistant coaches from rival staffs found him at the same satellite camp and started a quiet bidding war on the spot.",
      "His {hs} coach sent one unsolicited email that ended up reaching four programs by the end of the week.",
      "A junior-year highlight package, cut by a classmate for a media class, is what actually started this recruitment.",
      "The first real evaluator to watch him in person came to see a five-star at the same camp and left with two names.",
      "He was found the way a lot of {state} prospects are — through a coaching tree that runs three states deep.",
      "A recruiting service ranked him purely off measurables before anyone had actually watched the tape closely.",
      "The tape that got him found was two years old by the time a coordinator finally clicked on it.",
      "His name surfaced on a message board thread before it ever showed up on an official recruiting site.",
    ],
    rise: [
      "His junior-to-senior jump is the entire story — the rankings had not caught up when the offers started.",
      "A six-catch, three-touchdown regional playoff game rewrote his offer sheet in one night.",
      "He tested in the top tier at a spring camp and the credible programs moved within days.",
      "The rise was steady rather than explosive, which is why his board runs deep instead of top-heavy.",
      "He added a Power-conference offer in each of the last three months of his recruitment.",
      "Two schools that passed in the spring came back in November with real offers.",
      "His stock moved every time he played a ranked opponent, which happened four times.",
      "A late-season position change made him a more interesting evaluation for every staff on his list.",
      "He was a three-star in June and a high three-star with a Power-conference board by December.",
      "The rise came with a decommitment, which is how his recruitment finally turned competitive.",
      "His senior film did most of the heavy lifting — the junior tape had been easy to overlook.",
      "The offer list grew slowly, then all at once, after a nationally televised October game.",
      "He picked up three offers in a single week after a coordinator finally circulated his tape internally.",
      "The rise tracked almost exactly with his 40 time — as one dropped, the other climbed.",
      "A commitment from a rival prospect at his position opened a scholarship that went straight to him.",
      "His recruitment doubled in size the week a rival program's staff got fired mid-cycle.",
      "The offers came in a cluster after a summer all-star game nobody expected him to dominate the way he did.",
      "He turned one strong film session into a genuine bidding war among three programs in the same conference.",
      "His stock jumped the moment a rival evaluator publicly compared him to a recent NFL draft pick.",
      "The recruitment accelerated once his senior tape reached programs that had passed on his junior film.",
      "He added a real Power-conference option late, after a coordinator change reopened a board that had closed on him.",
    ],
    pitch: [
      "The pitch from every staff is the same: early rotational snaps, a starting job by year two.",
      "One school is selling a position change; the rest want him exactly where {hs} plays him now.",
      "There is a real NIL package at the top of his board, though nothing life-changing.",
      "Staffs are pitching him on one trait they believe becomes special with college coaching.",
      "Two coordinators have shown him install tape with his name written into the personnel groupings.",
      "The pitch at the top of his board is a two-deep with nobody older than a sophomore at his spot.",
      "One staff is selling development history; another is selling immediate snaps. He is weighing both fairly.",
      "The NIL money is real but modest, and every staff has been upfront about the number.",
      "A position coach with a track record at his exact profile is the entire pitch from the leader in the clubhouse.",
      "He has been promised a package of designed touches, which he has learned to be skeptical of.",
      "Staffs are pitching the conference schedule as hard as the program itself.",
      "The developmental pitch and the playing-time pitch are coming from different schools, and that is the whole decision.",
      "The pitch splits cleanly in two: one staff sells development, the other sells an immediate two-deep spot.",
      "Coaches are candid that the depth chart is wide open at his position, which he has taken as the entire sales pitch.",
      "One program is pitching him on a scheme built for his exact skill set; the rest are pitching potential.",
      "The NIL conversation here is modest and mostly theoretical, and every staff has said so upfront.",
      "A position coach with a track record of developing similar profiles is doing most of the recruiting himself.",
      "The pitch keeps circling back to one number: how many snaps he could realistically see as a true freshman.",
      "Every staff on his board has shown him the same install tape with slightly different personnel groupings.",
      "The most honest pitch he has heard so far promised nothing but an even competition in fall camp.",
      "Coaches are selling him on a redshirt that turns into a real role, not a lost year.",
    ],
    scope: [
      "It is a regional race with one national program hovering on the edge of it.",
      "Three schools are genuinely in it, all within a six-hour drive of {city}.",
      "The recruitment is competitive without turning into a circus, which suits him fine.",
      "He took all five official visits and reported back that two of them were formalities.",
      "The board is mostly regional with one outlier program from the other side of the country.",
      "Two conferences are represented on his final list, and both make geographic sense.",
      "His recruitment drew a modest crowd of local media and exactly zero national attention.",
      "The final four are all programs that have signed a player out of {city} in the last five years.",
      "He is the highest-rated prospect at {hs} in a decade, and the market is treating him accordingly.",
      "The race narrowed to two in November and stayed there through the December signing window.",
      "One staff flew a head coach in for an in-home visit, which settled a lot of it.",
      "The recruitment is regional by choice — he cut two national programs over distance alone.",
      "Staying close to {city} was never a stated priority, but every program on his short list happens to be.",
      "Three conferences are represented on his board, which for a player at his level is a genuinely wide net.",
      "The recruitment stayed under the radar nationally even as it heated up inside the region.",
      "He is deciding between a program two hours from home and one twelve states away, and both are live options.",
      "The board narrowed to three schools by December, each selling a different version of the same opportunity.",
      "This recruitment picked up more attention than most at his level, without ever turning into a circus.",
      "He took every visit his calendar allowed, which for a player outside the top rankings is unusual on its own.",
      "The recruitment is regional in practice, national in theory, and likely to end somewhere in between.",
      "Two in-state programs and one out-of-region wildcard make up the entirety of his real board.",
      "The market for him widened considerably after one program's staff made the case publicly.",
    ],
  },
  high: {
    found: [
      "National recruiters had him circled by his sophomore spring, before he played a full varsity season at {pos}.",
      "He was a priority target on every board in the region the day his junior film went public.",
      "The first offer came from {topOffer} before he turned 16, and the rest of the country followed within a month.",
      "Elite-camp invitations arrived unsolicited, which is the clearest tell in this whole process.",
      "He had 20 offers before his junior season started and stopped announcing them individually.",
      "Two national recruiting analysts had him in their top 50 before he ever attended a camp.",
      "Head coaches were showing up to {hs} spring practice, which the staff had never seen before.",
      "He was invited to three national events as a sophomore and won all three sessions.",
      "His film was already being dissected on national recruiting shows before his junior season ended.",
      "The {topOffer} staff made him their number-one target at the position in back-to-back cycles.",
      "He was the first player in {hs} history offered by a program in every Power conference.",
      "Recruiting services had him ranked before his own school newspaper had written a word about him.",
      "He was already a known name in the {state} recruiting community before he had thrown a single varsity pass.",
      "National evaluators had him rated off middle-school film, which is exactly as unusual as it sounds.",
      "Every major recruiting outlet had a writer assigned specifically to his recruitment by his sophomore year.",
      "He was the youngest player invited to a national showcase reserved almost entirely for seniors.",
      "Coaches from three time zones had already visited {hs} before his junior season kicked off.",
      "His recruitment was a national story before the {hs} student newspaper had run a single article about him.",
      "He was the first name mentioned when scouts talked about the {state} class, two full years before signing day.",
      "A five-minute mixtape uploaded by a family friend generated more traffic than the {hs} athletic department's entire website.",
      "He drew a full staff to a Tuesday practice — head coach included — the spring of his sophomore year.",
    ],
    rise: [
      "He won his session at a national elite camp and the offer count doubled inside a week.",
      "There was no rise to speak of — he has topped the {state} board since the day he arrived at {hs}.",
      "Head coaches, not coordinators, were the ones flying into {city} personally.",
      "He shut his recruitment down early, reopened it in November, and every staff came sprinting back.",
      "He climbed from a top-100 name to a top-15 name over one summer of camp performances.",
      "His senior tape did not move his ranking, because there was nowhere left for it to go.",
      "Two rival staffs both moved on position coaches over how his recruitment was handled internally.",
      "The rise happened inside one nationally televised game in September of his junior year.",
      "He went from a regional priority to a true national one after a single one-on-one rep in July.",
      "A viral camp rep in June put him on every recruiting front page in the country.",
      "By his senior opener, the only real question was which four schools would make the final cut.",
      "He was the consensus top player at his position in the country by the end of the summer circuit.",
      "There was never a rise because there was never a floor — he arrived a five-star and stayed one.",
      "He climbed to the top of the national board after a single camp rep that is still being replayed online.",
      "Every recruiting service moved him up a tier after the same nationally televised September performance.",
      "The rise was instant: one viral highlight, and every major program called within 48 hours.",
      "He was a top-100 name in June and the top player in the country by the December all-star circuit.",
      "His recruitment never had a quiet month — every ranking update moved him up, never down.",
      "The jump from regional star to national name happened over a single elite-camp weekend.",
      "He climbed past two more decorated recruits after a head-to-head rep at a national event settled the argument.",
      "The rise was steady and total — from a name on a watch list to the consensus best player at his position.",
    ],
    pitch: [
      "The NIL package at the top of his board is substantial and structured across multiple years.",
      "Every staff is promising day-one snaps, and at least two of them are telling him the truth.",
      "Coordinators are showing him install tape and telling him exactly which packages were built for him.",
      "He is being recruited as a program-changing piece, not as a roster addition.",
      "Two collectives have made competing multi-year offers, and both have leaked publicly.",
      "One head coach told him he would build the offense around him, on the record, in his living room.",
      "The pitch includes a jersey number that has not been issued at that program in fifteen years.",
      "Staffs are pitching him on a two-year college runway and an early draft exit.",
      "He has been promised the starting job in writing, which is as close to a lock as recruiting gets.",
      "A program flew his entire family in for a game-day visit and put them on the field for warmups.",
      "The NIL conversation has been handled by an agent since his junior year.",
      "Every pitch involves a direct comparison to a former player at that school who is now in the league.",
      "Every program on his board has already mapped out his entire position room around the assumption he signs.",
      "The NIL packages here are competitive at a level usually reserved for established college stars, not incoming freshmen.",
      "Two staffs have promised him the exact same jersey number, which has become its own small subplot.",
      "He is being recruited less like a prospect and more like a program's next decade of relevance.",
      "Coaches are pitching him with install tape that already has his name typed into the first-team reps.",
      "The pitch includes a personal position coach, a custom training plan, and a spot already carved out for a Heisman campaign.",
      "One staff brought in a former player at his position, now in the league, to make the pitch in person.",
      "Every school left on his board has already sold out season tickets banking partly on the idea he signs.",
      "The recruiting pitch has stopped being about football and started being about legacy and timing.",
    ],
    scope: [
      "This is a national recruitment. Three time zones, and the in-state school is not the favorite.",
      "He is the highest-rated prospect out of {city} in twenty years, and the market reflects it.",
      "The final list is national, elite, and functionally impossible to fake interest in.",
      "Anyone still saying they are in it after his last official visit is doing public relations.",
      "His commitment will be televised, which tells you everything about the scale of this recruitment.",
      "The final four programs have combined for six national titles — that is the level he is operating at.",
      "Every school on his list has produced a first-round pick at his position in the last decade.",
      "The recruitment has been covered nationally since his sophomore year and has never slowed down.",
      "The in-state program is in it, but only because they are genuinely elite, not because of geography.",
      "He is fielding calls from head coaches on a schedule his family had to formally organize.",
      "Two programs have been recruiting him since middle school, which is legal and still slightly unsettling.",
      "The national recruiting analysts covering his decision have already whiffed on it twice.",
      "The favorite has been chalk since the summer — everyone is just waiting on the paperwork.",
      "This recruitment has its own hashtag, which tells you everything about the scale before you watch a single snap.",
      "National television is covering his commitment ceremony live, an honor usually reserved for a handful of players a year.",
      "He is choosing among programs that have combined for a Heisman winner in each of the last three classes.",
      "The final decision will be litigated on national radio for a full week regardless of which way it goes.",
      "Every school still in it has a realistic case to make for a national championship within his four years there.",
      "This is the rare recruitment where the {hs} staff has had to hire outside help just to manage the media requests.",
      "The board has been the same four blue-blood programs for over a year, with no realistic fifth option ever emerging.",
      "He is a genuine industry event — analysts, radio hosts, and rival coaches all have a rooting interest in this decision.",
      "The recruitment has outgrown {city} entirely; it is a national story now, whether the family wanted that or not.",
    ],
  },
};

/* ------------------------------------------------------------------ */
/* College career narrative                                            */
/* ------------------------------------------------------------------ */

export const COLLEGE_OPENINGS: string[] = [
  "He enrolled at {college} in January and spent his first spring hearing he was not close to ready.",
  "{college} redshirted him immediately and put him on a 20-pound gain plan.",
  "He played 180 special-teams snaps as a true freshman at {college} and almost nothing else.",
  "The {college} staff moved him within a month of his arrival, and the new spot fit him better.",
  "He was the fourth {pos} on the {college} depth chart in August and the second by the bowl game.",
  "His first season at {college} was mostly a weight-room story; the tape from that spring is unrecognizable now.",
  "{college} threw him into the rotation in week three after an injury, and he never gave the job back.",
  "He arrived at {college} 18 pounds lighter than his listed weight and spent a year fixing that.",
  "The {college} staff told him he would redshirt, then played him in the opener out of necessity.",
  "He spent his first fall at {college} on the scout team, where he reportedly made life miserable for the starters.",
  "{college} signed three players at his position in his class, and he was the third-rated one of the group.",
  "His freshman year at {college} ended with 42 snaps and a very clear plan for the offseason.",
  "He was the only true freshman on the {college} travel roster at his position.",
  "The {college} strength staff still cites his first-year body-composition numbers as a program example.",
  "He came to {college} a quiet kid out of {city} and left the loudest voice in the position room.",
  "A coaching change in his first offseason at {college} nearly sent him into the portal before he ever played.",
  "{college} asked him to add weight, and he showed up in August 24 pounds heavier without losing a step.",
  "He tore a labrum in his first college camp and did not play a snap that season.",
  "The {college} staff put him in the two-deep in August and never seriously considered pulling him.",
  "He started his college career behind a senior who ended up getting drafted, which delayed everything by two years.",
  "{college} played him at three positions in his first two seasons before settling on one.",
  "He was academically ineligible for one game as a freshman and has spoken about it publicly since.",
  "The plan at {college} called for two years of development. He beat that timeline by a full season.",
  "He arrived on campus the highest-rated signee in the class and the least experienced player in the room.",
  "{college} put him on the field immediately because the alternative graded out worse.",
  "His first college start came on the road in a hostile environment, and the staff still brings it up.",
  "He spent his first two seasons at {college} in the room behind two future professionals.",
  "The {college} coaching staff had him in a rotational role by October of his true freshman year.",
  "He walked on at {college} with no scholarship and a chip that the staff still talks about years later.",
  "The {college} staff buried him on the depth chart as a true freshman, on purpose, to let him develop in private.",
  "He missed the entire first month of fall camp at {college} with a minor injury and still made the travel roster.",
  "{college} handed him the job in August of his true freshman year because the alternative was worse.",
  "He spent his first year at {college} rooming with a senior who taught him more than any coach did that season.",
  "The {college} coaching staff nearly redshirted him twice before a season-ending injury to a veteran changed the plan.",
  "He arrived at {college} as an early enrollee and was already ahead of the install by spring ball.",
  "{college} recruited him as an athlete and did not settle on a permanent position for him until his sophomore year.",
  "He turned down more famous programs to walk into a crowded {college} room and outwork every name ahead of him.",
  "The {college} staff nearly lost him to the transfer portal before he ever played a snap, and talked him off the ledge personally.",
  "He gained fifteen pounds of muscle in his first {college} offseason and looked like a different player by the opener.",
  "{college} played him out of position his entire true freshman year, a decision the staff now calls a mistake.",
  "He spent his true freshman season on the scout team, a fact the current starters at {college} still bring up to haunt him.",
  "The {college} strength staff flagged him as a program outlier before he had played a single competitive snap.",
  "He arrived at {college} unranked and left the first fall camp as the surprise name in every position meeting.",
  "{college} had four scholarship players ahead of him on the depth chart in August of his freshman year.",
  "He broke into the {college} lineup because of a suspension, not an injury, and simply never gave the spot back.",
  "The coaching change at {college} the summer after he signed nearly sent his commitment somewhere else entirely.",
  "He redshirted his true freshman year at {college} and used it to add the frame the staff had asked for.",
  "{college} started him as a true freshman purely out of necessity, and the growing pains showed up on tape that fall.",
];

/** Used instead of a standard opening when the player transferred. */
export const COLLEGE_TRANSFER_OPENINGS: string[] = [
  "He arrived at {college} with two years of starts on tape and was treated like a veteran immediately.",
  "The transfer to {college} is the hinge of his career — the role he was promised is the role he got.",
  "He landed at {college} in the winter portal window and was running with the first unit by the spring game.",
  "{college} recruited him out of the portal harder than most staffs recruit high-school seniors.",
  "The move to {college} put him in a scheme that finally asked him to do what he actually does well.",
  "He entered the portal on a Monday and had a {college} offer by Wednesday.",
  "{college} was the third school to call and the only one offering the job outright.",
  "He transferred up a level and did not look remotely out of place doing it.",
  "The first stop taught him how to practice. {college} is where that habit started producing.",
  "He left a program where he had started eleven games because {college} offered a bigger stage and took it.",
  "The portal move cost him a year of eligibility on paper and bought him two rounds on draft night.",
  "He arrived at {college} in June, learned the install in eight weeks, and started the opener.",
  "Coaches at {college} say the transition was the smoothest they have had with a portal addition.",
  "The transfer was about scheme, not playing time — he was already starting where he came from.",
  "He hit the portal after one coordinator change too many and found a staff at {college} that finally fit.",
  "The move to {college} was about touches, not money, though the two ended up arriving together.",
  "He entered the portal with three years of tape and left it two weeks later with the job locked down at {college}.",
  "{college} was the only program willing to guarantee him the exact role he had already earned elsewhere.",
  "He left a winning program for {college} purely because the depth chart at his old spot never moved.",
  "The transfer to {college} reunited him with a position coach who had recruited him out of high school originally.",
  "He spent one spring at {college} learning an entirely new scheme and looked more comfortable in it than the old one by fall.",
  "The portal decision came down to a single phone call from the {college} head coach, made personally and immediately.",
  "He left his first program with eligibility remaining and zero regrets, according to everyone who knows him at {college}.",
  "{college} beat out four other programs for him in the portal largely on the strength of one honest phone call.",
];

export const COLLEGE_BEATS: string[] = [
  "The jump came between his second and third seasons, when the game visibly slowed down for him.",
  "He took over as a full-time starter in the fall and led the position group in snaps by October.",
  "A new coordinator built a package specifically for him in the spring, and the production followed.",
  "His role expanded every month — situational to rotational to essential inside of one season.",
  "Two conference road games are the reason NFL area scouts started sending in reports on {college} practices.",
  "He played the last five games of the year through a shoulder issue that would have shelved most of the roster.",
  "The technique cleanup is the real story: the traits were always there, the footwork was not.",
  "He handled the full mental load by his third year — protections, checks, and the communication nobody credits.",
  "His best game came against the best defense on the schedule, which is not a small detail on a résumé.",
  "He was voted a team captain, and the {college} staff cites it before they cite any of the production.",
  "A midseason scheme change put him in position to make more plays, and he immediately made them.",
  "He led {college} in snaps at his position for two consecutive seasons.",
  "The staff started using him in packages nobody had drawn up for him a year earlier.",
  "He was the only player on the roster who never came off the field in the fourth quarter.",
  "His production against ranked opponents is materially better than his production against everybody else.",
  "He missed three games with a high-ankle sprain and came back to post his best two performances of the year.",
  "The {college} staff moved him to a new alignment in the spring and the numbers jumped 40 percent.",
  "He spent an offseason working with a private coach and came back with an entirely new technical base.",
  "A conference title game performance is the tape every evaluator opens first.",
  "He graded out as the highest-rated player on the {college} defense in five of twelve games.",
  "The coaching staff trusted him with the green dot in his final two seasons.",
  "He was double-teamed on roughly a third of his snaps as a senior, and the production held up anyway.",
  "His snap count nearly doubled between his sophomore and junior seasons.",
  "He played through a broken hand for a month, which is the story his position coach leads with.",
  "The {college} staff credits a film-study habit that started in his second year on campus.",
  "He never missed a practice in his last two seasons, which at his position is genuinely unusual.",
  "A nationally televised night game in October is where the draft conversation actually started.",
  "He set the {college} single-season record at his position and did it in eleven games.",
  "The improvement in his second full year as a starter is the most convincing thing on his résumé.",
  "He turned down a chance to sit out the bowl game and played 60 snaps in it anyway.",
  "His conditioning became a strength rather than a question somewhere around his third season.",
  "He added a genuine counter move to his game in the offseason, and the sack numbers doubled.",
  "Coaches began using him as the example in position meetings for younger players.",
  "He was the only player at his position to start every game across three seasons.",
  "The staff asked him to play out of position for four games due to injuries, and he did it without complaint.",
  "His third-down usage rate led the roster by a wide margin.",
  "He recorded production in every single game of his final season — the kind of consistency scouts flag.",
  "A rivalry-game performance in November is what pushed him from a day-two name to a day-one conversation.",
  "He made the conference's all-academic team three times, which teams genuinely do notice.",
  "The {college} staff moved a returning starter to accommodate him, which tells you what they thought of him.",
  "He worked his way from special teams to a starting role without ever hitting the portal.",
  "His pass-protection grade improved every year on campus, the least glamorous good sign there is.",
  "He handled a full position change in his final offseason and still graded out as a starter.",
  "Two different coordinators built game plans around the same trait, which is a real signal for evaluators.",
  "He earned a full scholarship midseason after arriving at {college} on a partial one, which the staff rarely does.",
  "The {college} staff moved his installed role twice in one season and he adjusted both times without missing a beat.",
  "He turned a two-game absence from injury into extra film study that showed up immediately once he returned.",
  "A single bowl-game performance is what actually put him on national radars after a quiet regular season.",
  "He earned first-team reps in fall camp over a returning starter, which set the tone for his entire college career.",
  "The staff started calling plays specifically to get him matchups he could win, and the box score reflects it.",
  "He played through a high-ankle sprain for the final month of the season and never once used it as an excuse.",
  "A midseason quarterback change at {college} completely reshaped his role, and he adapted faster than the staff expected.",
  "He turned a rough freshman tape into a completely rebuilt technical profile by his sophomore fall camp.",
  "The {college} strength staff calls his sophomore-to-junior jump the best body-composition change they have measured.",
  "He took over the green-dot responsibilities as a sophomore, a year ahead of the staff's own internal plan.",
  "A three-sack performance against a ranked opponent is the tape every team pulled up first.",
  "He never came off the field on defense for an entire season, which the {college} training staff calls remarkable.",
  "The staff credits an offseason position swap with unlocking a level of production nobody projected.",
  "He earned the trust of three different coordinators in as many years, which is its own kind of résumé.",
  "A dominant performance in the {college} spring game is what actually settled an open competition at his spot.",
  "He played the entire back half of the season on a bad shoulder and the tape barely shows the difference.",
  "The staff started using him on special teams purely to keep him involved while he worked his way up the depth chart.",
  "He set a new {college} program record for consistency at his position — production in every game, without exception.",
  "A single road environment, hostile beyond anything he had ever seen, is where evaluators say the transformation started.",
  "He added an entirely new skill to his game every offseason at {college}, which coaches say is genuinely rare.",
  "The staff moved a veteran starter to a new role specifically to keep both players on the field at once.",
  "He turned a benching early in his career into the best stretch of football he has ever played.",
  "A conference player-of-the-week honor as a sophomore is the first real signal that the staff's plan was working.",
  "He handled a full coordinator change in his final season without a dip in production, which evaluators flag as a real sign.",
];

export const COLLEGE_CLOSINGS: string[] = [
  "The traits translate cleanly. The question is whether the technique holds up against NFL length.",
  "He leaves {college} with a professional body, a professional routine, and a defined positional identity.",
  "Scouts see a plug-and-play starter inside of two years, with special-teams value in the meantime.",
  "He is being drafted for what he already does well, not for what he might eventually become.",
  "There is real developmental upside left, which is unusual for a prospect this far along mechanically.",
  "The floor is a long-term rotational piece. The ceiling is why people keep re-watching the tape.",
  "He declared with eligibility remaining, and no evaluator in the building argued against the decision.",
  "The medicals are clean and the interviews reportedly went even better than the tape did.",
  "He leaves as one of the most productive players in program history at the position.",
  "The evaluation comes down to whether a staff believes the last twelve games or the first thirty.",
  "He is a scheme-specific fit, and the right room could get a genuine starter out of a mid-round pick.",
  "The consensus is that he sits closer to his ceiling than most prospects in this range of the class.",
  "His pro day answered the speed question the fall tape had left open.",
  "Teams are split on the position he ultimately plays, which is either flexibility or a red flag depending who you ask.",
  "He will land somewhere between where the tape says and where the testing says, as always happens.",
  "The résumé checks every box: production, durability, leadership, and a clean file.",
  "He finished college a far better player than his recruiting ranking ever suggested he would be.",
  "Every team that scouted him came away with the same note about his practice habits.",
  "The tools are obvious. The consistency is the whole conversation in the draft room.",
  "He leaves {college} having outperformed his signing-day expectations by a wide margin.",
  "The final evaluation reads like a bet on the person as much as a bet on the player.",
  "He is the type who becomes somebody's favorite roster spot within two years.",
  "The floor is high enough that a worst-case outcome still looks like a long career as a backup.",
  "Nobody who watched him at {college} believes he is finished improving.",
  "The projection is starter — the only real disagreement in the room is about the timeline.",
  "He is the kind of prospect who tests average, grades well on tape, and outplays his eventual draft slot.",
  "Teams will spend the spring deciding whether the production or the traits are the real evaluation.",
  "He goes into the draft with a defined role, a clean medical file, and no real off-field questions.",
  "He checks a lot of boxes for a program looking for a translatable, plug-in-day-one starter.",
  "The tape is translatable enough that scheme fit barely enters the conversation.",
  "He is a safer selection than most in his range, with a lower ceiling to match the certainty.",
  "The traits alone would make him a wild card on the board; the tape is what settles it.",
  "He leaves {college} as close to a finished product as this level produces, with real room still on the frame.",
  "The tape says starter. The medicals say starter. The interviews, for once, say the same thing.",
  "He is the rare prospect whose floor and ceiling sit closer together than most evaluators are used to seeing.",
  "Teams project him as a Day 1 contributor with a legitimate path to more once the scheme fits are sorted out.",
  "He leaves {college} having answered every question except the one only the league itself can answer.",
  "The technique is already ahead of most of the class; the traits are why teams keep circling back for another look.",
  "He is exactly what his last two seasons of tape said he was, which is the highest compliment a scout can pay.",
  "The evaluation is settled: a translatable skill set, a clean file, and very little projection required.",
  "He leaves {college} with the kind of résumé that makes a mid-round grade look like a market inefficiency.",
  "Scouts keep using the word safe, which at his position is a genuine compliment rather than a criticism.",
  "He is a Day 2 lock with a Day 1 argument, depending entirely on how a given room values his position.",
  "The tape shows a player who is already coached up; the testing will decide how far the floor actually rises.",
  "He leaves {college} as the rare player whose national reputation actually undersold the tape.",
  "The medicals, the testing, and the film all point the same direction, which happens less often than fans assume.",
  "He is being drafted on production first and traits second, an order that suits exactly how he plays.",
  "The résumé reads clean from freshman year to declaration, without a single red flag anyone had to explain away.",
  "He leaves {college} a more complete player than the recruiting profile ever promised, and a safer bet because of it.",
  "Teams like the person as much as the player, which shows up in every background call anyone bothered to make.",
  "The evaluation is straightforward: a translatable role player with a chance to be more if the room is right.",
  "He is proof that a quiet recruitment and a loud college career are not mutually exclusive outcomes.",
];

/** Used when the development arc went the wrong way, so the close matches the story. */
export const COLLEGE_CLOSINGS_DOWN: string[] = [
  "He leaves {college} as a projection rather than a finished product, which is not where anyone expected this to end.",
  "Teams will draft the traits and hope a different building gets more out of them.",
  "The evaluation is a bet that the right coaching staff finds what {college} could not.",
  "He is a developmental pick now, and everyone involved has made peace with that reality.",
  "The floor is a backup and a special-teams contributor. The ceiling is the argument teams will have internally.",
  "Scouts keep going back to the high-school tape, which is rarely a good sign this late in a career.",
  "He will be somebody's fourth-day-of-camp surprise or he will not make a roster at all.",
  "The tools are still in there. Four years of evidence against him is the real problem.",
  "He leaves {college} with more questions than he arrived with, which is the whole story in one line.",
  "The medical file and the missed time will decide where he actually comes off the board.",
  "There is a version of this player who plays a decade. There is a version who never dresses.",
  "He is a project again, at 22, which is a hard sell in the back half of a draft class.",
  "He leaves {college} with a file thick enough that teams will spend more time on the medical staff's notes than the tape.",
  "The traits are still the pitch; four years of inconsistent tape is still the rebuttal.",
  "He is the kind of prospect a staff drafts on upside alone, fully aware of how often that bet does not pay off.",
  "The production never caught up to the recruiting hype, and the gap follows him straight into draft rooms.",
  "He leaves {college} having proven the traits are real and the consistency is still an open question.",
  "Teams will have to talk themselves into him, which is rarely a good sign this deep into a college career.",
  "The tape is uneven enough that two teams could watch the same four games and reach opposite conclusions.",
  "He is a boom-or-bust evaluation at a point in the process where most prospects have settled into something safer.",
  "The medical file alone will push him down boards that would otherwise have him rated much higher.",
  "He leaves {college} with more tools than production, which is the exact profile that keeps scouting departments up at night.",
];

/**
 * Production notes. These live in the college narrative, not underneath the
 * stat line — a stat line should be numbers and nothing else.
 */
export const COLLEGE_PRODUCTION_BEATS: string[] = [
  "He put his numbers up against a schedule with three top-25 defenses on it.",
  "The production came in a run-first system that capped his volume all year.",
  "He posted his best totals while missing two games in the middle of the season.",
  "Almost all of his production came after the coaching change in October.",
  "The efficiency numbers are better than the counting stats, which is his camp's whole argument.",
  "He produced as the clear focal point of every opposing game plan.",
  "His volume was modest by design — he shared a room with another draftable player.",
  "The counting stats undersell him; the per-snap numbers led the conference outright.",
  "He did it behind a line that started six different combinations across the year.",
  "Roughly 40 percent of his production came in the final four games of the season.",
  "He saw double coverage on a third of his routes and the numbers held up anyway.",
  "He was on a snap count for the first month and still led the team in production by December.",
  "His final line is a program record, and the man who held it before him is in the league.",
  "Two of his best games came in the biggest environments on the schedule.",
  "He played through a rotating cast of quarterbacks and the numbers held up regardless of who was throwing him the ball.",
  "The production dipped noticeably whenever {college} faced a top-25 defense, a real and fair question for evaluators.",
  "He put up his best numbers in his final four games, exactly when teams say it matters most.",
  "The stat line is modest by design — {college} ran a scheme that spread production across three players at his spot.",
  "He produced at a nearly identical rate home and away, which evaluators specifically look for and rarely find.",
  "His numbers came without a single game missed to injury across three full seasons.",
  "The production against ranked opponents alone would make for a quietly impressive career on its own.",
  "He posted a career high in his final college game, which staffs read as a player still trending upward.",
  "The counting stats lag the per-snap numbers by a wide margin, which is exactly the argument his camp is making.",
  "He did the bulk of his damage in the fourth quarter, when the games at {college} were actually still in question.",
];

/* ------------------------------------------------------------------ */
/* Development arc flavour                                             */
/* ------------------------------------------------------------------ */

export const ARC_BEATS: Record<string, string[]> = {
  generational: [
    "Nobody recruited him for this. The player he became at {college} bears almost no resemblance to the recruit.",
    "He is the reason coaching staffs keep taking swings on unranked kids with good frames.",
    "The gap between his recruiting profile and his draft profile is the largest in this class.",
    "Three years of development turned an afterthought into the best player on a good team.",
    "His high-school evaluation is now a case study in what film cannot tell you about a 17-year-old.",
    "The version of him that left {college} would not recognize the tape from his freshman year, and neither would the coaches who signed him.",
    "Nobody projected this outcome, including the {college} staff that recruited him purely on frame and hope.",
  ],
  breakout: [
    "The breakout came a year later than the staff expected and was worth the wait.",
    "He outplayed his recruiting ranking by a full tier, which the {college} staff predicted and nobody else did.",
    "The player who signed at {college} and the player who declared are not the same evaluation at all.",
    "His development curve turned sharply upward in year three and never came back down.",
    "He was a fallback signing who became a priority draft-day name.",
    "The breakout happened in full view of a national audience, in a game nobody expected him to matter in at all.",
    "He spent two years as a name on the depth chart before becoming the best player in the {college} building almost overnight.",
  ],
  riser: [
    "He got a little better every season, which is less dramatic and more reliable than a breakout.",
    "The improvement was incremental and constant — nothing about his rise was sudden.",
    "He signed as a solid prospect and leaves as a clearly better one.",
    "Each offseason added something specific, and the tape reflects every bit of it.",
    "Nothing about the climb was dramatic, which is exactly why some evaluators nearly missed it entirely.",
    "He added something real every single offseason at {college}, and the tape simply stacked up over time.",
  ],
  advertised: [
    "He is essentially the player he was projected to be, on schedule and without drama.",
    "The recruiting evaluation held up almost exactly, which happens more often than the internet suggests.",
    "No surprises here — the traits that got him recruited are the traits getting him drafted.",
    "He did what was expected of him, every year, without a single wasted season.",
    "He is close to chalk at this point — the evaluation has not moved in three years.",
    "The player who signed and the player who declared are, refreshingly, the exact same evaluation.",
    "There is no story here beyond the obvious one: he did what the recruiting profile said he would do, on schedule.",
  ],
  underwhelmed: [
    "The production never quite matched the billing, and staffs have spent three years explaining why.",
    "He was good. The recruiting profile said great, and that gap follows him into the draft.",
    "The tools showed up in flashes rather than across full games.",
    "He was a starter for three years without ever being the best player on his own field.",
    "The traits are still all there on tape; the results just never fully caught up to them at {college}.",
    "He was a good college player who was billed, fairly or not, as a future great one.",
  ],
  injuries: [
    "Two seasons were interrupted by injuries, and the healthy tape is genuinely good.",
    "The medical file is the entire conversation — the player, when available, was excellent.",
    "He missed 14 games across three years, which is the only thing keeping him out of the first round.",
    "Availability became the defining question of his college career through no real fault of his own.",
    "The healthy tape is good enough that teams keep circling back to it despite everything the medical file says.",
    "Availability, more than anything he did on the field, is the entire story of his time at {college}.",
  ],
  stalled: [
    "The development just never came. He is close to the same player he was as a freshman.",
    "Three coordinators, two position coaches, and no meaningful technical progress to show for it.",
    "The staff kept waiting for the leap and it never arrived.",
    "He plateaued after his second season, and the tape has looked the same since.",
    "Three different position coaches tried three different fixes at {college}, and none of them changed the outcome.",
    "The tools showed up in practice more often than they showed up on Saturdays, which is its own kind of verdict.",
  ],
  bust: [
    "He was one of the highest-rated players in his recruiting class and never started a full season.",
    "Something went wrong between signing day and now, and nobody involved will say what on the record.",
    "The recruiting ranking is now the least useful piece of information in his file.",
    "He lost his job twice, hit the portal once, and finished a rotational player.",
    "He was the headline of his signing class and a forgotten name on the {college} roster by his junior year.",
    "Nobody at {college} disputes the talent. Everybody at {college} has a different theory about what happened to it.",
  ],
};

/* ------------------------------------------------------------------ */
/* Stat-line templates                                                 */
/* ------------------------------------------------------------------ */

/**
 * Stat lines read as stat lines, not sentences — quicker to scan and short
 * enough to sit on one row next to everything else.
 */
export const HS_STAT_TEMPLATES: Record<Position, string[]> = {
  QB: [
    "{pyds} pass yds · {ptd} TD · {int} INT · {comp}% · {ryds} rush yds",
    "{comp}% · {pyds} yds · {ptd} TD · {int} INT",
  ],
  RB: [
    "{ryds} rush yds · {carries} car · {rtd} TD · {rec} rec",
    "{ryds} yds · {rtd} TD · {rec} rec, {recyds} yds",
  ],
  WR: [
    "{rec} rec · {recyds} yds · {rectd} TD",
    "{rec} rec · {recyds} yds · {rectd} TD · {ryds} rush yds",
  ],
  TE: [
    "{rec} rec · {recyds} yds · {rectd} TD",
    "{rec} rec · {recyds} yds · {snaps} in-line snaps",
  ],
  OL: [
    "{snaps} snaps · {pancakes} pancakes · {sacksAllowed} sacks allowed",
    "{grade}% grade · {snaps} snaps · {sacksAllowed} sacks allowed",
  ],
  "Edge Defender": [
    "{sacks} sacks · {tfl} TFL · {tkl} tkl · {ff} FF",
    "{sacks} sacks · {tfl} TFL · {qbh} QB hits",
  ],
  DT: [
    "{tkl} tkl · {sacks} sacks · {tfl} TFL · {ff} FF",
    "{tfl} TFL · {sacks} sacks · {qbh} QB hits",
  ],
  Linebacker: [
    "{tkl} tkl · {tfl} TFL · {sacks} sacks · {ints} INT",
    "{tkl} tkl · {tfl} TFL · {ff} FF",
  ],
  Cornerback: [
    "{ints} INT · {pbu} PBU · {tkl} tkl",
    "{ints} INT · {pbu} PBU · {targets} targets",
  ],
  Safety: [
    "{tkl} tkl · {ints} INT · {pbu} PBU · {tfl} TFL",
    "{tkl} tkl · {ints} INT · {ff} FF",
  ],
  "Kicker/Punter": [
    "{fg}/{fga} FG · long {long} · {touchbacks} TB",
    "{fg}/{fga} FG · {punts} punts, {punt} avg",
  ],
};

export const COLLEGE_STAT_TEMPLATES: Record<Position, string[]> = {
  QB: [
    "{pyds} pass yds · {ptd} TD · {int} INT · {comp}% · {ryds} rush yds",
    "{comp}% · {pyds} yds · {ptd} TD · {int} INT · {games} starts",
  ],
  RB: [
    "{ryds} rush yds · {ypc} ypc · {rtd} TD · {rec} rec",
    "{carries} car · {ryds} yds · {rtd} TD · {recyds} rec yds",
  ],
  WR: [
    "{rec} rec · {recyds} yds · {rectd} TD",
    "{rec} rec · {recyds} yds · {ypr} avg · {rectd} TD",
  ],
  TE: [
    "{rec} rec · {recyds} yds · {rectd} TD",
    "{rec} rec · {recyds} yds · {snaps} in-line snaps",
  ],
  OL: [
    "{snaps} snaps · {sacksAllowed} sacks allowed · {pressures} pressures",
    "{games} starts · {grade}% grade · {sacksAllowed} sacks allowed",
  ],
  "Edge Defender": [
    "{sacks} sacks · {tfl} TFL · {tkl} tkl · {qbh} QB hits",
    "{sacks} sacks · {pressures} pressures · {snaps} rush snaps",
  ],
  DT: [
    "{tkl} tkl · {sacks} sacks · {tfl} TFL · {qbh} QB hits",
    "{tfl} TFL · {pressures} pressures · {sacks} sacks",
  ],
  Linebacker: [
    "{tkl} tkl · {tfl} TFL · {sacks} sacks · {pbu} PBU",
    "{tkl} tkl · {tfl} TFL · {ints} INT · {ff} FF",
  ],
  Cornerback: [
    "{ints} INT · {pbu} PBU · {tkl} tkl · {targets} targets",
    "{pbu} PBU · {comp}% allowed · {ints} INT",
  ],
  Safety: [
    "{tkl} tkl · {ints} INT · {pbu} PBU · {tfl} TFL",
    "{tkl} tkl · {ints} INT · {ff} FF",
  ],
  "Kicker/Punter": [
    "{fg}/{fga} FG · long {long} · {touchbacks} TB",
    "{punts} punts · {punt} avg · {inside20} inside 20",
  ],
};

/* ------------------------------------------------------------------ */
/* Accolades                                                           */
/* ------------------------------------------------------------------ */

export const HS_ACCOLADE_BANKS: Record<RatingBand, string[]> = {
  low: [
    "All-league honorable mention",
    "Two-year varsity letterman",
    "Team captain as a senior",
    "All-district second team",
    "{mascot} most improved player",
    "All-county selection",
    "Team MVP as a senior",
    "Academic all-conference",
    "Scout-team player of the year as a sophomore",
    "All-area honorable mention",
    "{hs} iron-man award",
    "Special-teams player of the year",
  ],
  mid: [
    "First-team all-district",
    "All-state second team",
    "Conference player of the year",
    "Two-time all-conference selection",
    "Regional camp MVP",
    "{city} area player of the year",
    "Team captain, two years",
    "All-region first team",
    "District championship game MVP",
    "{state} top-100 recruit",
    "Two-time team MVP",
    "All-metro first team",
  ],
  high: [
    "First-team all-state",
    "{state} player of the year",
    "Under Armour All-America Game selection",
    "All-American Bowl invitation",
    "National elite-camp MVP",
    "Two-time first-team all-state",
    "State champion and title-game MVP",
    "National top-50 recruit",
    "{state} Gatorade Player of the Year",
    "Three-time all-conference selection",
    "Polynesian Bowl invitation",
    "Consensus five-star prospect",
  ],
};

export const HS_ACCOLADE_POSITION_EXTRAS: Partial<Record<Position, string[]>> = {
  QB: [
    "Elite 11 finalist",
    "State record for single-season passing efficiency",
    "Elite 11 regional MVP",
  ],
  RB: ["State record for rushing touchdowns in a season", "All-American Bowl running back of the week"],
  WR: ["National camp one-on-ones champion", "State record for receiving yards in a game"],
  TE: ["Tight end U camp standout", "All-state at two positions"],
  OL: [
    "Lineman of the year, {state}",
    "OL Masterminds camp standout",
    "Trench-warfare camp champion",
  ],
  "Edge Defender": ["Defensive player of the year, {state}", "State record for single-season sacks"],
  DT: ["Big-man camp MVP", "All-state defensive lineman, two years"],
  Linebacker: ["Linebacker of the year, {city} area", "Defensive MVP of the state title game"],
  Cornerback: [
    "Defensive back of the year, {city} area",
    "One-on-ones champion at a national camp",
  ],
  Safety: ["All-state defensive back, two seasons", "Defensive back camp MVP"],
  "Kicker/Punter": [
    "Kohl's national camp top-10 finish",
    "Five-star kicking camp rating",
    "State record for longest field goal",
  ],
};

export const COLLEGE_ACCOLADE_BANKS: Record<RatingBand, string[]> = {
  low: [
    "Two-year starter at {college}",
    "Team special-teams award",
    "Academic all-conference",
    "Honorable mention all-conference",
    "{college} most improved player",
    "Scout-team player of the year",
    "Conference all-academic team",
    "{college} iron-man award",
  ],
  mid: [
    "Second-team all-conference",
    "Two-time all-conference honorable mention",
    "{college} team captain",
    "Bowl game MVP",
    "All-conference third team",
    "{college} defensive player of the year",
    "Conference championship game MVP",
    "Senior Bowl invitation",
  ],
  high: [
    "Consensus All-American",
    "First-team all-conference, two seasons",
    "Conference player of the year",
    "Unanimous All-American as a junior",
    "{college} team captain and conference defensive player of the year",
    "Two-time first-team All-American",
    "Conference championship game MVP",
    "National player of the year finalist",
  ],
};

export const COLLEGE_ACCOLADE_POSITION_EXTRAS: Partial<Record<Position, string[]>> = {
  QB: ["Davey O'Brien Award semifinalist", "Heisman Trophy finalist", "Manning Award finalist"],
  RB: ["Doak Walker Award finalist", "Maxwell Award semifinalist"],
  WR: ["Biletnikoff Award finalist", "Hornung Award semifinalist"],
  TE: ["Mackey Award semifinalist", "Mackey Award finalist"],
  OL: ["Outland Trophy semifinalist", "Rimington Trophy watch list", "Lombardi Award finalist"],
  "Edge Defender": ["Ted Hendricks Award finalist", "Bednarik Award semifinalist"],
  DT: ["Outland Trophy finalist", "Nagurski Trophy semifinalist"],
  Linebacker: ["Butkus Award semifinalist", "Bednarik Award finalist"],
  Cornerback: ["Jim Thorpe Award finalist", "Nagurski Trophy watch list"],
  Safety: ["Jim Thorpe Award semifinalist", "Bednarik Award watch list"],
  "Kicker/Punter": ["Lou Groza Award semifinalist", "Ray Guy Award finalist"],
};

/**
 * The actual win, not just the nomination. Reserved for the very top of the
 * grade range (see the `elite` gate in buildAccolades) so it stays rare —
 * being a finalist is common at 9.4+, actually winning is not.
 */
export const COLLEGE_ACCOLADE_POSITION_ELITE: Partial<Record<Position, string[]>> = {
  QB: ["Heisman Trophy winner", "Davey O'Brien Award winner"],
  RB: ["Doak Walker Award winner", "Heisman Trophy winner"],
  WR: ["Biletnikoff Award winner"],
  TE: ["Mackey Award winner"],
  OL: ["Outland Trophy winner"],
  "Edge Defender": ["Ted Hendricks Award winner"],
  DT: ["Outland Trophy winner"],
  Linebacker: ["Butkus Award winner"],
  Cornerback: ["Jim Thorpe Award winner"],
  Safety: ["Jim Thorpe Award winner"],
  "Kicker/Punter": ["Lou Groza Award winner", "Ray Guy Award winner"],
};

/** Position-agnostic capstone honor, used when a position has no elite award of its own. */
export const COLLEGE_ACCOLADE_ELITE_UNIVERSAL: string[] = [
  "Walter Camp Award winner",
  "Unanimous national player of the year",
  "AP College Football Player of the Year",
];

/* ------------------------------------------------------------------ */
/* Transfer language                                                   */
/* ------------------------------------------------------------------ */

export const TRANSFER_REASONS: string[] = [
  "after a coaching change",
  "after two seasons buried on the depth chart",
  "following a coordinator change in the spring",
  "after starting eleven games as a sophomore",
  "for a bigger role and a bigger stage",
  "after his position coach left for the NFL",
  "in the winter portal window",
  "after a scheme change he did not fit",
  "chasing a defined starting job",
  "after his second season was cut short by injury",
  "when the program signed two players at his position",
  "for a chance to play closer to home",
];
